### ISSUE TITLE
else no funciona correctamente

### ISSUE THREAD

**Issue by Jandresgomez** [dserrano3/Discant#5]
![captura de pantalla 2014-09-27 a la s 12 49 20](https://cloud.githubusercontent.com/assets/8940723/4431599/d0146264-466e-11e4-863c-65a0d25e1ec1.png)
![captura de pantalla 2014-09-27 a la s 12 51 40](https://cloud.githubusercontent.com/assets/8940723/4431601/fa692a72-466e-11e4-93f7-74ca2c3e7dd3.png)

solo funciona si esta en la linea del corchete anterior del if

**Comment by dserrano3** [comment]
Creo que ya esta arreglado, gracias por el comentario!!
